### ISSUE TITLE
Release server down

### ISSUE THREAD

**Issue by safaci2000** [pragmagrid/tstat#8]
Maybe having a tagged release on github would be a nice alternative when the primary server is down?

```
wget http://tstat.polito.it/download/tstat-3.1.1.tar.gz                                                                                                       (minikube/default)
--2020-08-07 10:20:07--  http://tstat.polito.it/download/tstat-3.1.1.tar.gz
Resolving tstat.polito.it (tstat.polito.it)... 130.192.9.220
Connecting to tstat.polito.it (tstat.polito.it)|130.192.9.220|:80... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2020-08-07 10:21:24--  (try: 2)  http://tstat.polito.it/download/tstat-3.1.1.tar.gz
Connecting to tstat.polito.it (tstat.polito.it)|130.192.9.220|:80... connected.
HTTP request sent, awaiting response... No data received.
Retrying.

--2020-08-07 10:22:41--  (try: 3)  http://tstat.polito.it/download/tstat-3.1.1.tar.gz
Connecting to tstat.polito.it (tstat.polito.it)|130.192.9.220|:80... connected.
HTTP request sent, awaiting response...

```

**Comment by ayuthmang** [comment]
I just tested, it is able to download.

Is it great to upload build files to the [GitHub release](https://github.com/pragmagrid/tstat/releases/new)?

**Comment by safaci2000** [comment]
Yeah, confirmed that it works again.  The reason i mentioned github is to ensure that it's not dependent on your server being up and running.  It's always nice to have a mirror out there. 

Also, since I wasn't able to re-create the binary from the source code, see issue #9 it becomes more critical.  

Just my 2 cents.  Thanks for hosting this and all the work for this project in general.

Feel free to close this, confirmed that works now.

**Comment by ayuthmang** [comment]
I just realized, last year I containerized tstat and published to Dockerhub, in case of anyone who wants to try or the hosting server is down.

The repo is available here: https://github.com/blacksourcez/tstat-docker.
Docker Hub: https://hub.docker.com/r/blacksourcez/tstat/.

Feel free to use, fork, and create PR if you wanted to.
